### ISSUE TITLE
lb new finds duplicate titles in the text

### ISSUE THREAD

**Issue by IlyaMZP** [LukeSmithxyz/lb#7] opened 2018-10-17 23:42 UTC
https://github.com/IlyaMZP/lb/commit/127ce26a7e8b7333a4eead2f26f50a26d4993e6b
Here I've tried to solve the issue.
But that broke deletion.

**Comment by IlyaMZP** [comment] 2018-10-18 00:11
https://github.com/IlyaMZP/lb/commit/4584ddfd4ec309e000a56d4154453cc52e98f4b8
Now it works.

**Comment by flippyy** [comment] 2018-10-25 20:50
I think this is a duplicate of #6, so that means it got fixed when Luke fixed that one.

**Comment by IlyaMZP** [comment] 2018-10-26 17:45
No. That is a different problem. It creates "something-1.html" instead of "something.html" even without post with the same name, because it searches for the whole text, not just IDs with names.

**Closed** 2018-12-14 17:39 UTC
